### ISSUE TITLE
台灣模型庫的自動串接貼圖問題

### ISSUE THREAD

**Issue by babaair** [SaiZyca/AutoPBRMapper#1]
你好，我是在台灣數位模型庫下載你的auto pbrmapper的使用者，我用的是blender2.93，跟你們ppt裡提到的2.8有點版本上的落差，但我不確定是不是因為這樣導致我跟著你ppt裡面的教學影片照做卻沒辦法將我的模型自動導入貼圖，而且一些新增的欄位在這外掛中，希望我沒有點錯導致貼圖無法自動導入!

**Comment by babaair** [comment]
[](url)

**Comment by SaiZyca** [comment]
目前更新支援 3.0 ，應該都修正了請下載後試試。

**Comment by babaair** [comment]
好的謝謝

SaiZyca ***@***.***> 於 2022年2月10日 週四 下午6:01 寫道：
